# workspace.yml
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: greetings
spec:
  organization: patrickmunne
  secretsMountPath: "/tmp/secrets"
  module:
    source: "terraform-aws-modules/sqs/aws"
    version: "3.5.0"
  outputs:
    - key: url
      moduleOutputName: sqs_queue_id
  variables:
    - key: name
      value: greetings
      sensitive: false
      environmentVariable: false
    - key: fifo_queue
      value: "false"
      sensitive: false
      environmentVariable: false
    - key: AWS_DEFAULT_REGION
      valueFrom:
        configMapKeyRef:
          name: aws-configuration
          key: region
      sensitive: false
      environmentVariable: true
    - key: AWS_ACCESS_KEY_ID
      sensitive: true
      environmentVariable: true
    - key: AWS_SECRET_ACCESS_KEY
      sensitive: true
      environmentVariable: true
    - key: AWS_SESSION_TOKEN
      sensitive: true
      environmentVariable: true  
    - key: CONFIRM_DESTROY
      value: "1"
      sensitive: false
      environmentVariable: true
